
Public class VariableExo {
    public static void exo1() {

    //Create a variable named carName and assign the value Volvo to it.

String carName="Volvo";
    }
                public static void exo2() {

//Create a variable named maxSpeed and assign the value 120 to it.

int maxSpeed= 120;
                }
                        public static void exo3() {

//Display the sum of 5 + 10, using two variables: x and y.

int x= 5;
int y = 10;
System.out.println(x + y);
                        }
                                public static void exo4() {

//Create a variable called z, assign x + y to it, and display the result.

int x = 5;
int y = 10;
int z= x + y;
System.out.println(z);
                                }
                                        public static void exo5() {

//Fill in the missing parts to create three variables of the same type, using a comma-separated list:


int x = 5, y = 6, z = 50;
System.out.println(x + y + z);
                                        }
}